# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.Mood'),
        ),
    ]
