# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-24 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0003_auto_20180514_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.CharField(max_length=10)),
                ('deadline', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.Mood'),
        ),
    ]
